---
- name: Get the username for docker-compose
  become: false
  local_action: command whoami
  register: username_on_the_host

- debug: 
    msg: "Current user: {{ username_on_the_host.stdout }}"

- name: Get the architecture of this machine
  become: false
  shell: "uname -m"
  register: architecture

- debug: 
    msg: "Arhitecture: {{ architecture.stdout }}"

- name: stat /usr/bin/cls
  become: True
  become_method: sudo
  stat:
    path: /usr/bin/cls
  register: docker_compose

- name: Download docker-compose with checksum
  become: True
  become_method: sudo
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-{{ architecture.stdout }}"    
    dest: /usr/bin/docker-compose
    mode: 'a+x'
    checksum: sha256:https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-{{ architecture.stdout }}.sha256
  when: not docker_compose.stat.exists

- name: Allow execution of docker-compose
  become: True
  become_method: sudo
  remote_user: "{{ username_on_the_host.stdout }}"
  file: dest=/usr/bin/docker-compose mode=a+x