---
- name: Install gcc
  become: True
  become_method: sudo
  package:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - gcc
      - cmake
      - gdb

- name: Install build-essential
  become: True
  become_method: sudo
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: "yes"
  vars:
    packages:
      - build-essential
  when:
    ansible_distribution in ("Ubuntu", "Linux Mint", "Pop!_OS")

- name: Install the Development tools
  become: True
  become_method: sudo
  ansible.builtin.dnf:
    name: '@Development tools'
    state: present
  when: ansible_distribution == 'Fedora'

- name: Check gcc version
  shell: gcc --version

- name: Link to the new location of the file 'vmlinux.xz'
  become: True
  become_method: sudo
  shell: ln -sf /usr/lib/modules/$(uname -r)/vmlinux.xz /boot/